### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by flavioope** [Majored/mcm-js-api-wrapper#5]
Hello I am trying to use the API but every time I try to use any method it gives me this error `HeaderMalformedError: The 'Authorization' header was malformed or not in an expected format.` could you help me?

**Comment by Majored** [comment]
I've just tested by creating a fresh project with the first example provided in the README and everything's working fine.

It's more likely that you've provided an invalid token. Feel free to open a support ticket onsite via: https://builtbybit.com/tickets/new

**Comment by flavioope** [comment]
One more question, should I use the private or shared token, maybe that's it?

**Comment by Majored** [comment]
That entirely depends on your use case. As per our [wiki documentation page](https://builtbybit.com/wiki/ultimate-api/):
> We support two types of tokens that grant varied access to our endpoints. The primary token type, 'Private', grants access to all public endpoints and as the name suggests, should be kept private. This token type grants access to view and modify potentially sensitive data specific to your account.
>
>Alternatively, we also support a secondary 'Shared' token type that grants very limited access to our API and can be shared with other members or within your products. This token type grants access to public validation of resource licenses, public version checking and public update checking. However, its scope is limited to your account and the resources you've authored solely.

**Comment by flavioope** [comment]
Ok, thank you very much, try again and verify the token.
